"""Add name to Container table

Revision ID: baabff92aeb4
Revises: d89666f7f137
Create Date: 2023-03-13 19:59:34.572379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baabff92aeb4'
down_revision = 'd89666f7f137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_container_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
