"""Add role to Container table

Revision ID: d89666f7f137
Revises: 6d1c571bcbf6
Create Date: 2023-03-13 19:31:42.414020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89666f7f137'
down_revision = '6d1c571bcbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_container_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
